resources:
- name: <%= app['name'] %>
  type: git
  source:
    uri: <%= app['git'] %>
    branch: <%= app['branch'] || DEFAULT_BRANCH %>
    version:
      ref: <%= app['git_ref'] %>

- name: <%= app['name'] %>-image
  type: docker-image
  source:
    repository: <%= dockerhub_from_git app['git'] %>
    tag: <%= app['git_ref'] %>
    email: "{{dockerhub_email}}"
    username: "{{dockerhub_user}}"
    password: "{{dockerhub_pass}}"

jobs:
- name: build-<%= app['name'] %>-image
  public: true
  plan:
  - get: <%= app['name'] %>
    trigger: true
  <% if app['config']['build'] %>
  <% build = app['config']['build'] %>
  - task: build-<%= app['name'] %>
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: <%= build['docker']['repo'] %>
          tag: <%= build['docker']['tag'] %>
      inputs:
      - name: <%= app['name'] %>
      outputs:
      - name: build-output
      <% for name, val in (build['params'] || []) %>
      params:
        <%= name %>: <%= val %>
      <% end %>
      run:
        path: bash
        dir: build-output
        args:
          - -c
          - cp -a ../<%= app['name'] %>/{.??,}* . ; <%= build['run'] %>
  <% end %>
  - put: <%= app['name'] %>-image
    params:
      build: >
        <% if app['config']['build'] %>
          build-output
        <% else %>
          <%= app['name'] %>
        <% end %>
    get_params:
      skip_download: true
