---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: <%= pipeline[:name] %>
spec:
  rules:
<% for app in pipeline[:runnables] %>
  - host: <%= app['name'] %>.<%= pipeline[:name] %>.<%= pipeline[:biodome]['domain'] %>
    http:
      paths:
      - backend:
          serviceName: <%= app['name'] %>-service
          servicePort: <%= app['port'] %>
<% end %>
<% for app in pipeline[:runnables] %>
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: <%= app['name'] %>
  name: <%= app['name'] %>-service
spec:
  ports:
    - name: <%= app['name'] %>-port
      port: <%= app['port'] %>
      protocol: <%= app['protocol'] %>
      targetPort: <%= app['unique_port'] %>
  selector:
    name: <%= app['name'] %>
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <%= app['name'] %>
spec:
  replicas: 1
  template:
    metadata:
      name: <%= app['name'] %>
      labels:
        name: <%= app['name'] %>
    spec:
      containers:
      - name: <%= app['name'] %>-container
        image: <%= app['dockerhub'] %>
        ports:
        - name: <%= app['name'] %>-port
          containerPort: <%= app['unique_port'] %>
        env:
        - name: PORT
          value: "<%= app['unique_port'] %>"
        - name: UNIQUE_APP_ID
          value: <%= app['name'] %>
        <% for name, value in (pipeline[:env] || []) %>
        - name: <%= name %>
          value: <%= value %>
        <% end %>
<% end %>
